# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'puddle2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for puddle2
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  target 'puddle2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'puddle2UITests' do
    # Pods for testing
  end

end
